### ISSUE TITLE
Playback according to tempo

### ISSUE THREAD

**Issue by robyarmenio** [kulek1/guitar-tab-maker-issues#1]
It would be great to have the playback going accordingly to the time set when the tab gets saved into the local storage.

Keep doing the great job! Yours is a very simple, no frills, easy to use tab maker: something that I always have struggled to find to write tabs for my own band.

**Comment by kulek1** [comment]
I'm pleased to announce that it's now possible to set a custom tempo for playback. :) 
<img width="64" alt="Screenshot 2023-12-12 at 22 01 35" src="https://github.com/kulek1/guitar-tab-maker-issues/assets/7605514/ad0882c1-7202-408e-84f0-44f7a4134812">

Automatic tempo loading based on saved songs in the browser will be added in the next release as an enhancement to the new functionality.
