### ISSUE TITLE
Palm Mutes

### ISSUE THREAD

**Issue by CherryBomb828** [kulek1/guitar-tab-maker-issues#10]
This might already be there and i just cant find it, but it would be nice to to be able to add palm mutes to the tab

**Comment by kulek1** [comment]
Thank you for suggesting this. I'll add the `PM` symbol to my `todo` list

**Comment by kulek1** [comment]
@CherryBomb828 I've just released a new feature that allows you to add any text to tabs. Let me know if it works for you :) 

<img width="757" alt="Screenshot 2024-02-05 at 21 42 45" src="https://github.com/kulek1/guitar-tab-maker-issues/assets/7605514/ef4c00be-0fac-4c16-ab16-63caa9244f5f">

**Comment by CherryBomb828** [comment]
I can't figure out how you add the text

**Comment by kulek1** [comment]
which application version do you have? 
To add a text, select a tab by clicking on any column. You should be able to see a small text above the selected tab which is editable on click.

**Comment by CherryBomb828** [comment]
4.2.0, on firefox and windows 10, if that makes any difference
When i select any column the text input only appears over the first colum and theres no way i can find to get it to appear anywhere else
![Capture](https://github.com/kulek1/guitar-tab-maker-issues/assets/155577062/5d8fc792-e463-45a5-9447-1950c4a3c7d6)
![Capture1](https://github.com/kulek1/guitar-tab-maker-issues/assets/155577062/a02f03b7-5ee7-4953-9502-09d7b475cffd)

**Comment by kulek1** [comment]
@CherryBomb828 The current implementation works in such a way that you have to add enough spaces to add text over a particular column. It's a compromise between the flexibility of adding lyrics and short symbols like PM.

In a nutshell, each tab can have one line of text.

**Comment by CherryBomb828** [comment]
ah ok, then how in this screenshot:
<img width="757" alt="302427782-ef4c00be-0fac-4c16-ab16-63caa9244f5f" src="https://github.com/kulek1/guitar-tab-maker-issues/assets/155577062/3d205464-1bcc-48e3-bfec-4da3de0ede23">
did you manage to get the PM so far over to the right

**Comment by kulek1** [comment]
@CherryBomb828 I was just adding extra spaces using Spacebar key on the keyboard 😅
To make it faster, you can copy `                      ` multiple blank spaces and paste it
