### ISSUE TITLE
Missing a few Features, i would love to see

### ISSUE THREAD

**Issue by JetFlightGit** [kulek1/guitar-tab-maker-issues#11]
Hey,
really love your Tab Maker compared to all of the others out there. I do have few suggestion which would make it much better, for me atleast.

1. Make an optional notes section under each Tablature. Maybe even above columns aswell. Sometime it helps having the general Shape on top. For example i can Write Am on top i know the general shape for my hand. 
2. Love the chord finder would be nice if you can add a column with the suggest notes. So when i look up a G for example i can for example add it instead of filling out the column myself
3. Is there a way to delete the rests aswell? I see i can delete notes but not the rests
4. Able top play all Tablature at ones

Not sure if everything makes sense but I hope it does :)

Keep it up!

**Comment by kulek1** [comment]
Hey, 
I appreciate the feedback :)

I'd like to clarify #3 to make sure we're on the same page. You would like to have an option to keep notes from selected "column" and delete all other notes from the tab?
Could you also give some examples where #3 & #4 would be useful?

**Comment by kulek1** [comment]
Regarding #2:
Added in `v3.2.1` :)

**Comment by JetFlightGit** [comment]
> Regarding #2: Added in `v3.2.1` :)

I just saw, really nice :) One small suggestion regarding that feature. If you can make the Finder case insensitive. Just a small quality of life.

**Comment by JetFlightGit** [comment]
> Hey, I appreciate the feedback :)
> 
> I'd like to clarify #3 to make sure we're on the same page. You would like to have an option to keep notes from selected "column" and delete all other notes from the tab? Could you also give some examples where #3 & #4 would be useful?

Regarding #3: 
![image](https://github.com/kulek1/guitar-tab-maker-issues/assets/46763079/a13801c2-3a36-4650-99d5-c79e0545c89b)

Regarding #1:
![image](https://github.com/kulek1/guitar-tab-maker-issues/assets/46763079/796b9c9b-144e-4786-adc9-ebec76d29f17)
After looking a bit more into this would also be nice if you then also can add those chord shapes onto of your sheet. For beginners you just look at the created sheet instead of looking up those chords then. Just used painted which maybe helps it show: 
![image](https://github.com/kulek1/guitar-tab-maker-issues/assets/46763079/098e9302-0a37-4f12-9e2b-472f4d209f22)

#4: I am organizing my sheets in different Tablature for cleaner view but its still the same piece. So be able to play all would be benefital but that would still just be a quality of life since you can just click through them all and play them separately after one another.

Sry for my bad english but hope that clears some things up :)

**Comment by kulek1** [comment]
@JetFlightGit 
ℹ️ 3. option to remove selected column has been released in v3.4.0 :)

**Comment by kulek1** [comment]
> > Regarding #2: Added in `v3.2.1` :)
> 
> I just saw, really nice :) One small suggestion regarding that feature. If you can make the Finder case insensitive. Just a small quality of life.

Done ✅

**Comment by kulek1** [comment]
@JetFlightGit happy to announce that the first feature request on the list (and kind of the last) has been added to the application in v4.2.0:

<img width="757" alt="Screenshot 2024-02-05 at 21 42 45" src="https://github.com/kulek1/guitar-tab-maker-issues/assets/7605514/001b5957-9198-49aa-9959-b3031708a998">
