### ISSUE TITLE
Add an ability to remove selected columns

### ISSUE THREAD

**Issue by oleksii-novikov** [kulek1/guitar-tab-maker-issues#12]
Add an ability to remove (not clear) selected columns. 

I would like to have the ability to remove selected columns so that I can adjust the pauses between the sounds.

**Comment by kulek1** [comment]
Good idea! Will add this

**Comment by kulek1** [comment]
@oleksii-novikov option to remove selected column has been released in v3.4.0 :)

**Comment by oleksii-novikov** [comment]
> @oleksii-novikov option to remove selected column has been released in v3.4.0 :)

thanks a lot!

**Comment by saltypepitas** [comment]
Hello! I was wondering if there could be a remove column option on mobile browser? I'm a Firefox user, if that's extra info you need
