### ISSUE TITLE
Remove Column & Copy Tb (for Ediitting)

### ISSUE THREAD

**Issue by garretmolloy** [kulek1/guitar-tab-maker-issues#13]
1. I can add columns - to increase spacing  - but I Cannot see how to remove or delete a column?

2. Copy Tab
3. Copy Column

Above I have a chord or piece of music I want to reuse and modify - it would be nice to be able to copy (highlighted column + CTRL-C) and then paste a column (Highlight new column and CTRL-V)

Similarly - if I have a Tab I like and want to copy it and then amend the copy - that would be nice "Duplicate Tab"/"Make Copy of highlighted Tab"?

**Comment by kulek1** [comment]
Thanks for the suggestion!

1. already reported here: https://github.com/kulek1/guitar-tab-maker-issues/issues/12 
2 & 3 - I'll add it in the future

**Comment by kulek1** [comment]
@garretmolloy 
the feature request #12 has been added in v3.4.0 :)

**Comment by kulek1** [comment]
@garretmolloy Copy/paste feature for selected columns have been added in v3.6.0 😎
The option to duplicate tabs will probably be added in the future, so I'm closing this issue for now
