### ISSUE TITLE
Hammer and pullofs

### ISSUE THREAD

**Issue by Unrapid** [kulek1/guitar-tab-maker-issues#15]
**Describe the bug**
This may be a user error, but when I use the hammer-on and pull-of button, I click play to listen to it and the audio completely ignores the hammer-on and pull-off sounds, it just plays the notes listed

**To Reproduce**
1. Go to The menu
2. Click on 'Hammer-on'
3. Scroll down to 'Click any 2 notes'
4. See error doesn't play the sound

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by kulek1** [comment]
@Unrapid Thanks for the report! 
Currently, hammer-ons and pull-offs are not supported, but I'll see what I can do as other feature requests are addressed

**Comment by kulek1** [comment]
@Unrapid Basic support for hammer-ons and pull-offs has been added in v4.0.3 🎉
