### ISSUE TITLE
Import feature

### ISSUE THREAD

**Issue by EvilEngine-9** [kulek1/guitar-tab-maker-issues#18]
Hey,

love this, well done!

Any way you can import the saved/exported Tabs, so that someone else can import them on their computer?

Thanks a lot :)

**Comment by kulek1** [comment]
hey @EvilEngine-9,
thanks! Unfortunately, there's no easy way to import created tabs into another computer/browser but I'll think about adding something like that ;)

**Comment by kulek1** [comment]
Good news, the feature is now available in v4.1.0 :) 🎉 

<img width="396" alt="Screenshot 2024-01-30 at 20 05 49" src="https://github.com/kulek1/guitar-tab-maker-issues/assets/7605514/73814850-b7c7-43f0-a18a-de0e460715a6">

**Comment by EvilEngine-9** [comment]
You're amazingly quick! Appreciate it!

Don't like the payment options for donations. Do you have a PayPal-Email, you would share with me?

Ty. :)

**Comment by kulek1** [comment]
> You're amazingly quick! Appreciate it!
> 
> Don't like the payment options for donations. Do you have a PayPal-Email, you would share with me?
> 
> Ty. :)

You're welcome! 
I'm glad that the application is useful for you 🎶

**Comment by kulek1** [comment]
@EvilEngine-9 
I do have a paypal if you want to support me:
https://www.paypal.com/donate/?business=CB5239FWUHRRU&no_recurring=0&item_name=Thank+you+for+supporting+my+work+%F0%9F%92%99&currency_code=PLN

**Comment by EvilEngine-9** [comment]
Sweet, sent a little support. Keep it up, bro. :)
