### ISSUE TITLE
How do I delete spaces?

### ISSUE THREAD

**Issue by Aitornado8** [kulek1/guitar-tab-maker-issues#19]
I've been looking for how to delete spaces and I really didn't wanted to open a issue in here just for that, but I don't find anything. How do I do it? (Another thing is that I've been trying with the shortcuts and some doesn't work, Idk if I'm the only one with the shortcuts problem)

**Comment by kulek1** [comment]
@Aitornado8 have you tried to use the keyboard shortcut as it is described here?
<img width="461" alt="Screenshot 2024-01-30 at 18 54 02" src="https://github.com/kulek1/guitar-tab-maker-issues/assets/7605514/75d530bb-d04b-461c-b8b7-c9d8a48392ab">

If it doesn't work then please let me know which operating system and browser you have :)

**Comment by Aitornado8** [comment]
Hello!! Yeah, I have tried the keyboard shortcut and nothing. Right now I'm using Windows 11 and OperaGX, I actually tried this some days ago when I begun a tab compilation. I thought there could be a button as the insert space one. But yeah, sometimes I have to delete more changes to delete that space/column.

**Comment by kulek1** [comment]
Okay, let me investigate it why it doesn't work on your side.


>  I thought there could be a button as the insert space one

There's no enough space for all functionality but I agree, it would be easier to have such button

**Comment by kulek1** [comment]
@Aitornado8 
Can you try to use CTRL+Backspace instead?

**Comment by Aitornado8** [comment]
YEAAAAH THANK YOU SO MUCH:''DDDD

**Comment by chr2013** [comment]
Crtl Backspace do not work :( no way to remove 
Why did you don't add an icon ?
