### ISSUE TITLE
Hotkey for "insert space"

### ISSUE THREAD

**Issue by ThomasLastName** [kulek1/guitar-tab-maker-issues#2]
Am I the only one who expects either the space bar or the right arrow to create a new space? It's not a big deal, but the time of writing, the "insert space" button is hidden in the menu.

**Comment by kulek1** [comment]
Thanks for the suggestion! Both spacebar and right arrow keys are already reserved for other actions but maybe I'll bind another key like `n` for a new space

**Comment by kulek1** [comment]
Added two new shortcuts in v2.1.0:
- `T` for adding tablatures
- `S` for adding space in tab
<img width="451" alt="Screenshot 2023-12-06 at 18 35 29" src="https://github.com/kulek1/guitar-tab-maker-issues/assets/7605514/0b39cd71-3907-4c35-98be-461bbc4d3256">
