### ISSUE TITLE
Export as text or copy and paste as text

### ISSUE THREAD

**Issue by vtrduque** [kulek1/guitar-tab-maker-issues#20]
**Is your feature request related to a problem? Please describe.**
When I'm trying to copy and paste to another place (e.g. Telegram/G. Docs), it doesnt paste every char in line.
![image](https://github.com/kulek1/guitar-tab-maker-issues/assets/18485461/970f67a8-3173-40bb-b445-4ee4509ccced)

Expected:
![image](https://github.com/kulek1/guitar-tab-maker-issues/assets/18485461/bccba556-9631-455c-bd08-1e67f8ab331b)

**Describe the solution you'd like**
Two thing could be a solution.
1 - Copy as inline text
2 - Export it as a text file

**Describe alternatives you've considered**
Screen shot it 😅 

Just loved the project and hope it goes really far man =)

**Comment by kulek1** [comment]
hey @vtrduque, 
have you tried to use "_Export to TEXT_" option instead?

Using copy/paste directly from the editor might not be the best solution as tabs are not displayed in a format that you can just put into another text file. 
The app supports copy/paste though but it's only for copying single columns and pasting it into the same or another tab inside the editor.

<img width="269" alt="Screenshot 2024-01-31 at 18 32 43" src="https://github.com/kulek1/guitar-tab-maker-issues/assets/7605514/6919a0e1-e790-48f1-8052-3d9c453dc736">

**Comment by vtrduque** [comment]
bravo!
