### ISSUE TITLE
C Standard Tuning Support

### ISSUE THREAD

**Issue by hatfarm** [kulek1/guitar-tab-maker-issues#21]
**Is your feature request related to a problem? Please describe.**
There are lots of bands that use C Standard tuning.  It's 2 full steps down from standard tuning, and it is C-F-A♯-D♯-G-C or C-F-B♭-E♭-G-C

**Describe the solution you'd like**
I'd love to see support for this in the free tab maker.

**Describe alternatives you've considered**
I considered trying to add it myself, but since it's closed source, I'm unable to.

**Additional context**
Specifically, I'm putting together tabs for the band Pile, and this is the tuning they use on all of their songs, so it'd be a big deal for folks who want to create tab for them.

**Comment by kulek1** [comment]
Added in v4.1.2 ✅ 

<img width="479" alt="Screenshot 2024-01-31 at 18 30 58" src="https://github.com/kulek1/guitar-tab-maker-issues/assets/7605514/7f2b83c0-af21-4f22-816e-b077d38bf9bd">
