### ISSUE TITLE
Import tabs from another browser

### ISSUE THREAD

**Issue by dariy-vel** [kulek1/guitar-tab-maker-issues#22]
As far as I understand, all the tabs are stored in the browser's local storage. So if I change my PC, or change my browser, I'd lose all access to editing of the existing tabs I have.

I'd like to see a feature to export a tab to a file (may be some custom format) to be able to import it later.

Or am I missing something and there's a way to import tab sources?

**Comment by kulek1** [comment]
There's no backup feature yet, so for now you can use this option (`Copy a link to share`) to share tabs between different computers or browsers:
<img width="248" alt="Screenshot 2024-01-31 at 17 17 09" src="https://github.com/kulek1/guitar-tab-maker-issues/assets/7605514/7bad15de-46e9-4afa-9996-5a8970fd140d">

**Comment by owex** [comment]
> There's no backup feature yet, so for now you can use this option (`Copy a link to share`) to share tabs between different computers or browsers: <img alt="Screenshot 2024-01-31 at 17 17 09" width="248" src="https://private-user-images.githubusercontent.com/7605514/301230770-7bad15de-46e9-4afa-9996-5a8970fd140d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDcwNzMyNDAsIm5iZiI6MTcwNzA3Mjk0MCwicGF0aCI6Ii83NjA1NTE0LzMwMTIzMDc3MC03YmFkMTVkZS00NmU5LTRhZmEtOTk5Ni01YTg5NzBmZDE0MGQucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDIwNCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAyMDRUMTg1NTQwWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NzUwYzQwM2Y4YzM0NTYyY2IzYmNlMzkyOTYwZmE3N2IwNWM2NTZhNGIxNmRkNGM4ZjRjYTUwNWNjYzE1MzE4MiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.Du0LbtChvf5bZfnI9WqYP77EIJZONN37p_ZpQKIeHYk">

Great work with this! I'm jealous and curious how you solved the browser url length limitation, some funky algo?

**Comment by kulek1** [comment]
> Great work with this! I'm jealous and curious how you solved the browser url length limitation, some funky algo?

Thanks! Yeah, custom algorithm

**Comment by kulek1** [comment]
> As far as I understand, all the tabs are stored in the browser's local storage. So if I change my PC, or change my browser, I'd lose all access to editing of the existing tabs I have.
> 
> I'd like to see a feature to export a tab to a file (may be some custom format) to be able to import it later.
> 
> Or am I missing something and there's a way to import tab sources?

@dariy-vel  Your request has been addressed and the backup feature is now available in the latest version - v4.4.0 🎉 
cc: @Aitornado8

**Comment by dariy-vel** [comment]
Thank you so much! Trying it out
