### ISSUE TITLE
Drop B????

### ISSUE THREAD

**Issue by sanicbo** [kulek1/guitar-tab-maker-issues#23]
Is there any way y'all could add drop B so I can make tabs in that tuning?

**Comment by kulek1** [comment]
You can select your custom tuning by clicking on the open notes on the fret:
<img width="147" alt="Screenshot 2024-02-01 at 06 58 54" src="https://github.com/kulek1/guitar-tab-maker-issues/assets/7605514/0ca180fd-575e-497c-b114-7fd3094c8529">

**Comment by kulek1** [comment]
Released in v4.2.0
