### ISSUE TITLE
Ctrl+Z and Ctrl+S

### ISSUE THREAD

**Issue by rainshen49** [kulek1/guitar-tab-maker-issues#25]
**Describe the solution you'd like**
As a programmer myself, Ctrl+Z and Ctrl+S has been second nature to me. I notice the save and undo features already exist. Just need to wire them to keyboard shortcuts.

**Describe alternatives you've considered**

**Additional context**

**Comment by kulek1** [comment]
I like it 👍 
Added in v4.3.0 🎉
