### ISSUE TITLE
Error message suggested to clear cache, clearing cache resulted in loss of tabs

### ISSUE THREAD

**Issue by pattrickrice** [kulek1/guitar-tab-maker-issues#26]
**Describe the bug**
Tried to load the app and got an error message. I should have screenshotted the console as well for the exact error but this is all I have. After clearing cache, it seems like there was a loss of data. 

**To Reproduce**
1. encounter error message
2. clear cache
3. observe tabs are no longer present

**Expected behavior**

Honestly not certain. Maybe the ability to dump the data before clearing? At least an additional warning that clearing the cache will result in loss of data if everything is stored locally.

**Screenshots**

<img width="987" alt="Screenshot 2024-02-18 at 1 44 58 PM" src="https://github.com/kulek1/guitar-tab-maker-issues/assets/20763171/80aca05e-7f97-4911-997d-73c48d882004">

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] MacOS
 - Browser [e.g. chrome, safari] Chrome

**Smartphone (please complete the following information):**

**Additional context**

**Comment by kulek1** [comment]
@pattrickrice I'm really sorry for losing your data. I'll try to find the root cause that happened on your machine.
I've updated the error message to warn users that clearing the browser cache will result in a data loss.

Do you know exactly when the error occurred and what version you had?

**Comment by kulek1** [comment]
@pattrickrice I managed to find the problem and fix it so you don't have to worry about it anymore. 

Thank you for the report and I hope it won't discourage you from using TabMaker 😢

**Comment by pattrickrice** [comment]
No worries about the loss! Only a handful of songs but much appreciated that the software is free 🙂 unfortunately no I didn't capture the error or the version number. But the warning sounds like an improvement to me!
