### ISSUE TITLE
Add better rhythm guides

### ISSUE THREAD

**Issue by ggutie53** [kulek1/guitar-tab-maker-issues#27]
**Is your feature request related to a problem? Please describe.**
It feels like I'm guessing how long each note is on the tab, it isn't very clear how long each column is even with the bpm.

**Describe the solution you'd like**
Add a way to specify note length below the tablature to make it easier to follow along while writing and while listening. 

**Describe alternatives you've considered**
I've considered maybe trying an actual sheet music program but I don't know many and my sheet music reading is rusty, especially on a guitar which is not my main instrument.

**Additional context**

**Comment by kulek1** [comment]
I've thought a lot about this and I don't think it makes sense to create a whole new rhythm notation for tabs. To be honest, it sounds like you need sheet music. 
I'll think about adding it in the future, but it's a huge project to develop and then implement into TabMaker.
I'm closing this issue for now but feel free to re-open if needed.
