### ISSUE TITLE
Alternate tuning request - D-A-E-A-C#-E

### ISSUE THREAD

**Issue by EliLouvir** [kulek1/guitar-tab-maker-issues#29]
**Is your feature request related to a problem? Please describe.**
Not a problem, just would like to add another tuning option

**Describe the solution you'd like**
As a TabMaker user, I would like to be able to select an alternate tuning, D-A-E-A-C#-E, so I can preview chords and see tabs in the tuning I use the most. 

**Describe alternatives you've considered**
The software says I can add my own open notes but I can't seem to do that 

**Additional context**
This is awesome, I use it almost every day.  Thanks!

**Comment by kulek1** [comment]
Thank you for the report and support!

I'll add the new tuning to the app soon but in the meantime you can add your own custom tuning by clicking on the open notes here:
<img width="127" alt="Screenshot 2024-03-26 at 18 19 13" src="https://github.com/kulek1/guitar-tab-maker-issues/assets/7605514/cfb7af3a-bd26-4589-b398-da9b54f41918">

basically each open note is clickable 😄 

Please let me know if you have any more questions related to this functionality or TabMaker in general. I'm happy to help :)

**Comment by kulek1** [comment]
<img width="464" alt="Screenshot 2024-03-26 at 18 28 21" src="https://github.com/kulek1/guitar-tab-maker-issues/assets/7605514/a775e65d-0e71-4d02-9512-6c4e4ecdd727">

Released in v4.9.8 🎉
