### ISSUE TITLE
Duplicate Tablature

### ISSUE THREAD

**Issue by marcieldeg** [kulek1/guitar-tab-maker-issues#30]
The capability to replicate a tablature would prove to be exceedingly beneficial. I have composed a tablature integrating two distinct parts and am now in the pursuit of segregating it into two separate tablatures. Should there be a functionality allowing for the duplication of tablatures, I could simply eliminate the segments that are not pertinent.

Alternatively, the introduction of a feature enabling the division of the tablature at a specific juncture could serve as a feasible solution.

**Comment by kulek1** [comment]
Sounds like a good idea!

**Comment by kulek1** [comment]
Released in v5.1.0 🎉 
<img width="357" alt="Screenshot 2024-04-02 at 17 43 37" src="https://github.com/kulek1/guitar-tab-maker-issues/assets/7605514/59767dee-fb43-409c-b1b9-1556c62ef9ff">
