### ISSUE TITLE
Arpeggio+Strum 

### ISSUE THREAD

**Issue by isousa2** [kulek1/guitar-tab-maker-issues#32]
**Is your feature request related to a problem? Please describe.**
- No, just a new feature.

**Describe the solution you'd like**
- A new letter each for arpeggiating and strumming a chord; perhaps a and s, which adds their respective symbols and sounds to the tabs; a squiggly line and an arrow up/down, respectively. 

**Describe alternatives you've considered**
- A way to simulate strumming/arpeggiating more indirectly. Not sure how, though; sorry.

**Comment by kulek1** [comment]
Thanks for the report! 
Is there a chance that you could give some examples of tabs with this feature that you'd like to see implemented into TabMaker?

**Comment by isousa2** [comment]
Sure! Here is strumming notation:
![image](https://github.com/kulek1/guitar-tab-maker-issues/assets/158532538/484179f1-bfff-49be-9212-cfc9d19a941a)

And here is arpeggiating notation: 
![image](https://github.com/kulek1/guitar-tab-maker-issues/assets/158532538/aa92853f-547d-42cd-a409-a56b95abe23e)

I can provide examples of what it sounds like too, if you'd like.

**Comment by kulek1** [comment]
Thanks for the examples!
Unfortunately, text-based tabs have some limitations when it comes to custom symbols, so I don't see a way to implement such a feature at the moment.

As a workaround, I'd suggest applying `v`, `_` or `˽` characters over tabs by using the text feature that is already available in the TabMaker:
<img width="194" alt="arpeggio and strum on TabMaker - tab-maker.com" src="https://github.com/kulek1/guitar-tab-maker-issues/assets/7605514/669e71f1-9c3f-4985-b9d7-e81be1af7ed9">

**Comment by isousa2** [comment]
Ah, ok. That's understandable. Thanks!
