### ISSUE TITLE
Flag a note as palm muted?

### ISSUE THREAD

**Issue by madquantum69** [kulek1/guitar-tab-maker-issues#33]
Hello, is there anything that we can use to mark a note as palm muted?

**Comment by kulek1** [comment]
<img width="202" alt="Screenshot 2024-04-15 at 19 04 56" src="https://github.com/kulek1/guitar-tab-maker-issues/assets/7605514/c6604d14-8692-400e-b68b-75f2ac30c707">

Hey @madquantum69,
you can use the text feature to add any symbols you want above each tab :)

**Comment by madquantum69** [comment]
Awesome thank you very much!

**Comment by kulek1** [comment]
Marking it as resolved but feel free to re-open it if you have any more questions related to this functionality
