### ISSUE TITLE
No way to remove a position

### ISSUE THREAD

**Issue by chr2013** [kulek1/guitar-tab-maker-issues#35]
**Describe the bug**
No way to remove a position

**To Reproduce**
Try to remove a part of a song, no way to push left the rest already writen

If you add a space, OK, but no way to remove space ???

**Comment by chr2013** [comment]
tryed CTRL+Backspace but do not work...

Will you add a push buton ?

**Comment by kulek1** [comment]
@chr2013 what browser and operating system do you use?
