### ISSUE TITLE
Chords visualizer

### ISSUE THREAD

**Issue by M15TRAL** [kulek1/guitar-tab-maker-issues#36]
Hi,

Could you consider a feature which could help visualise the chords? 
For example if we click on a bar which plays a D7, a pictogram of the note pops up.
![ex](https://github.com/kulek1/guitar-tab-maker-issues/assets/94076068/196d7c4f-45e2-49f5-a79f-bec2415a38bc)

I think it would be cool to help beginners practice.
Thanks for your app though!

**Comment by kulek1** [comment]
Hi 👋 
Thanks for the suggestion! I'll add it to my list

**Comment by kulek1** [comment]
@M15TRAL The feature has been released in v5.5.0 🎉 
Let me know what you think :) 

<img width="249" alt="Screenshot 2024-06-23 at 22 56 13" src="https://github.com/kulek1/guitar-tab-maker-issues/assets/7605514/a01339fb-8e8b-43a5-9d6d-363338e30d45">
