### ISSUE TITLE
Export to text file

### ISSUE THREAD

**Issue by danbord** [kulek1/guitar-tab-maker-issues#37]
Cannot export to a text file?  Or I didn't found the way to do it?

**Comment by kulek1** [comment]
<img width="583" alt="Screenshot 2024-05-01 at 16 04 00" src="https://github.com/kulek1/guitar-tab-maker-issues/assets/7605514/af83a7a4-8aa8-4159-a1ab-eb973a154c9f">

You can :)

**Comment by danbord** [comment]
wow, super responsive. Thank you!  

The only export I found is in the settngis menu which export the json as a jwt.  Wonder why you are encoding it as a jwt.  Jwt is limited to 8Kb you may encouter some issues at some point

**Comment by kulek1** [comment]
Which option are you talking about? I'm asking because I don't encode anything to jwt so I'm a little bit confused 😅

**Comment by danbord** [comment]
Here :

<img width="503" alt="image" src="https://github.com/kulek1/guitar-tab-maker-issues/assets/18286902/79159b4b-8d89-4760-8e8f-fba1c8003455">

If I copy/paste the exported file contents it looked like a jwt.  I verified on jwt.io :

![image](https://github.com/kulek1/guitar-tab-maker-issues/assets/18286902/42b79dcf-4fda-4d6d-b76b-6316cf4b4aff)

**Comment by kulek1** [comment]
This is only for the backup if you want to move tabs to another browser and it's a simple base64 so don't worry about the size :)

**Comment by danbord** [comment]
Never realized an encoded jwt is just a base64 encoded json! hehe.  Thanks keep up the good work
