### ISSUE TITLE
shorter playback notes

### ISSUE THREAD

**Issue by deividu** [kulek1/guitar-tab-maker-issues#38]
Hello! I love your tab maker, but when I hit play, the notes keep playing, overlapping each other. Not even muting the next note stops them from playinh.

**Comment by kulek1** [comment]
Hey @deividu,

Could you share a link to the tab with notes that are overlapping each other? 

<img width="224" alt="Screenshot 2024-05-08 at 15 09 13" src="https://github.com/kulek1/guitar-tab-maker-issues/assets/7605514/69b3f0f2-4c97-4d17-bbb1-70b397019efa">

**Comment by deividu** [comment]
https://tab-maker.com/en/app?shareLink=XQAAAAIEAQAAAAAAAABtAGxQdDCfeWOUBU39xg_ET9LJedxx9WOiwkb4IxMZM2NXw5bZtVoc5-UgvyFKasGk7KCZ_yloit4n3r9TUVJgrSGbC9oRcjJGoKHt3svCWkhjBNXy4hBZaJYDER9M66CUPP4woMA

**Comment by deividu** [comment]
as trying to make a bass tab for this song: https://soundcloud.com/hiquegomez/guedali?in=hiquegomez/sets/o-teatro-do-disco-solar&utm_source=clipboard&utm_medium=text&utm_campaign=social_sharing

**Comment by kulek1** [comment]
Thanks! I'll see what I can do with it :)

**Comment by kulek1** [comment]
I've released a new version v5.1.4 🎉 
Let me know if it's better :)

**Comment by deividu** [comment]
GREAAATT!! <3
