### ISSUE TITLE
Prompt to save if current tab is not yet saved

### ISSUE THREAD

**Issue by onethirdzero** [kulek1/guitar-tab-maker-issues#39]
**Is your feature request related to a problem? Please describe.**
1. I open a new blank tab. I immediately save it as `Tab A`.
2. I then write some tabs on the current page.
3. I now choose to load `Tab A` sidebar.
4. The app does not give the user a heads up that the current tab is not yet saved. It immediately loads `Tab A`, which is a blank tab.

This means that all my work in step 2 is immediately lost. Hitting cmd/ctrl+z or Undo does not bring the previous work back.

**Describe the solution you'd like**
The app prompts the user to save the current tab (if it has not already been saved) before starting a potentially destructive action — eg. closing the browser window, loading a saved tab, etc.

**Describe alternatives you've considered**
N/A

**Additional context**
I lost 2 hours of work like this because I thought the current tab would be saved to a previous save file.

**Comment by kulek1** [comment]
Thanks for the suggestion and sorry for losing your tab!

The confirmation modal has been added in v5.1.5:
<img width="465" alt="Screenshot 2024-05-13 at 16 57 22" src="https://github.com/kulek1/guitar-tab-maker-issues/assets/7605514/b9edcd29-6461-4734-bbbd-bb0d2cd6984b">
