### ISSUE TITLE
line seperation

### ISSUE THREAD

**Issue by MaxWhitten** [kulek1/guitar-tab-maker-issues#40]
When my tabs get too long it goes over the screen, and then I have to scroll to see the playhead. Also, when exporting tabs they are too long and go outside of the pdf and you can't see them.

Automatically detect when tab is getting to close to the edge and make a new line that is appropriately sized for both the screen and a pdf.

A button that would split the tab into multiple lines wherever the cursor is and have the playhead jump to the next line when it reaches the end.

I found this yesterday when I had to tab a song for a school project and it really is a lifesaver. All the alternatives are either hard to use, ugly, or paid. This is amazing and would love to continue to see development happen! Keep up the good work.

**Comment by kulek1** [comment]
Thanks for the suggestion! 
The idea of scrolling and not automatically folding tabs in the preview is intentional, because I want the user to decide how the tabs should look. However, having a button to split it to the next line is a good idea and I'll try to implement it :)

**Comment by MaxWhitten** [comment]
Perhaps you could add a checkbox in settings for autoplay? That way anyone who wants it can turn it on, but if you don't you can leave it how it is.

**Comment by kulek1** [comment]
> Perhaps you could add a checkbox in settings for autoplay? That way anyone who wants it can turn it on, but if you don't you can leave it how it is.

You mean a checkbox for folding tabs if they don't fit on the screen?

**Comment by MaxWhitten** [comment]
Yeah that, but also maybe one for the playhead automatically jumping to the next line.

**Comment by nathan-charrois** [comment]
+1 for option to autoplay next tab/line

After adding an Intro, Verse, and Outro. When I press "Play" (or space) only one of the sections will play (Firefox v126). It would be awesome if the next section would auto play after the current section ends

Ps. Thank you for building this awesome tool!

**Comment by kulek1** [comment]
@MaxWhitten @nathan-charrois 
Alright, I've added a new loop mode that plays one tab in a loop. If the option is off, the playback will play all tabs from the selected tab to the end of all tabs, so that should cover your use case.
Let me know guys how it works :) 

<img width="72" alt="Screenshot 2024-07-04 at 17 22 10" src="https://github.com/kulek1/guitar-tab-maker-issues/assets/7605514/fa07a80c-4216-4a7a-9f53-7094436240ad">

PS. The new feature has been released in v5.8.0

**Comment by kulek1** [comment]
> A button that would split the tab into multiple lines wherever the cursor is and have the playhead jump to the next line when it reaches the end.

@MaxWhitten I've just added a new keyboard shortcut `/` to split tabs :)
I'm closing this issue since most of the stuff has been addressed. Feel free to open a new one if needed.
