### ISSUE TITLE
Help Section

### ISSUE THREAD

**Issue by dev0ured** [kulek1/guitar-tab-maker-issues#41]
Would be nice to have a section where you can look up the meaning of the different symbols like x,~,p etc.

**Comment by kulek1** [comment]
<img width="516" alt="Screenshot" src="https://github.com/kulek1/guitar-tab-maker-issues/assets/7605514/ff36f67b-9efd-4655-b8f1-2fed7eaf01ff">

Added in v5.2.0 🎉
