### ISSUE TITLE
Add Support for 5-String Banjo

### ISSUE THREAD

**Issue by Sebastan12** [kulek1/guitar-tab-maker-issues#43]
**Is your feature request related to a problem? Please describe.**
I wanted to make tabs for the 5-string banjo in open G tuning and am hopeful it could be added :D

**Describe the solution you'd like**
I would love to have the ability to select a 5 string banjo in standard open G tuning
![image](https://github.com/kulek1/guitar-tab-maker-issues/assets/12416169/d1d347e7-4b77-42dc-a970-7da34fe0010e)

Example of the notes
![image](https://github.com/kulek1/guitar-tab-maker-issues/assets/12416169/31c7692f-5b63-44ed-a183-3472c34db135)

**Describe alternatives you've considered**

Using another tool or developing one myself - but that is more of a hassle than extending the nice software you guys have made :D

**Additional context**

**Comment by kulek1** [comment]
Thanks for the request! 
I've added it to the todo list :)

**Comment by kulek1** [comment]
Banjo support has been added in v5.3.0 :) 

Let me know if it works well for you

**Comment by Sebastan12** [comment]
Yoooo thank you! - it works :D
