### ISSUE TITLE
Adding alternate tunings

### ISSUE THREAD

**Issue by Space-Cadet-Stuff** [kulek1/guitar-tab-maker-issues#44]
Lack of tuning options for bass guitar (4 String)

Requesting new options for drop tunings, alternate tunings and standard tunings.

Drop B, Drop A, D Standard, C Standard, etc.

**Comment by kulek1** [comment]
Added in v5.4.0 🎉

____
Support me on https://buymeacoffee.com/tabmaker/ ❤️
