### ISSUE TITLE
New Instrument. Ukulele

### ISSUE THREAD

**Issue by claudiobonfati** [kulek1/guitar-tab-maker-issues#46]
**Is your feature request related to a problem? Please describe.**
I want to create tablatures for the Ukulele, but it is not currently an option in Tab Maker options.

**Describe the solution you'd like**
Add the ukulele as a selectable instrument in Tab Maker, including its standard tuning (G-C-E-A).

**Describe alternatives you've considered**
I've looked at other software that supports ukulele tablature, but I prefer to use Tablature Maker. Manually adjusting tablatures for other instruments is also an option, but it's time-consuming.

**Comment by kulek1** [comment]
Ukulele support has been added in v5.6.0 🎉 
<img width="448" alt="Screenshot 2024-06-24 at 16 22 36" src="https://github.com/kulek1/guitar-tab-maker-issues/assets/7605514/4c2202a5-90c4-4d92-a7e7-ff3da958b00b">

Let me know how it works :)
