### ISSUE TITLE
Spaces not included in PDF export

### ISSUE THREAD

**Issue by cjonasw** [kulek1/guitar-tab-maker-issues#47]
**Describe the bug**
When adding spaces to tabs, they are removed when exporting as PDF.

**To Reproduce**
1. Go to add spaces in tab
2. Click on Export to PDF
3. Error: Spaces are not included

**Expected behavior**
Spaces included in PDF, like Text export.

**Screenshots**

<img width="356" alt="Screenshot 2024-06-24 at 12 04 31" src="https://github.com/kulek1/guitar-tab-maker-issues/assets/4989248/f3cc80ae-bb73-40fb-a206-baae5af6c859">

<img width="697" alt="Screenshot 2024-06-24 at 12 04 36" src="https://github.com/kulek1/guitar-tab-maker-issues/assets/4989248/356a19b9-166f-4964-bdcc-a61495fd9ba8">

**Desktop (please complete the following information):**
 - OS: iOS
 - Browser: Firefox

**Comment by kulek1** [comment]
@cjonasw hey, have you tried to use `Print / PDF` option instead? It supports all features compared to `Export to PDF` option which is a bit wonky.
<img width="212" alt="Screenshot 2024-06-24 at 16 24 40" src="https://github.com/kulek1/guitar-tab-maker-issues/assets/7605514/c3a55476-74d8-4b35-b20a-77383bb88744">

**Comment by cjonasw** [comment]
Yep this is what I used in the end, but would be nice to use the "pretty" view that the Export produces. Happy to help?

**Comment by kulek1** [comment]
Added a small improvement but wouldn't expect to be perfect. 
I'm planning to deprecate this function in the feature so I highly recommend using `Print / PDF` though.
