### ISSUE TITLE
A start play countdown

### ISSUE THREAD

**Issue by yahelihol** [kulek1/guitar-tab-maker-issues#48]
I want to play while the track is moving, and I'd like an option to play a 4-beat countdown or some other buffer time before it starts playing. 

A toggle button in the settings to enable a 4-beat wait every time I press play would be nice.

I could add empty bars before, but that would change the tab. and also, adding a tab before the first one is hard and counter-intuitive,

Tnx :)

**Comment by kulek1** [comment]
Released in v5.7.0 🎉
