### ISSUE TITLE
Add Chord Symbol Lettering Above Tablature

### ISSUE THREAD

**Issue by nashsolon** [kulek1/guitar-tab-maker-issues#49]
**Is your feature request related to a problem? Please describe.**
No problem related to this feature request

**Describe the solution you'd like**
I want the option to include a Chord Symbol above any line in the tablature.

**Describe alternatives you've considered**
Currently, I am inserting these symbols myself using the text bar above the tabs. Is that the intended use for that text box?

**Additional context**
See the screenshot below for the desired outcome
![easy-guitar-tabs-for-beginners_house-of-the-rising-sun](https://github.com/kulek1/guitar-tab-maker-issues/assets/59846310/1875a41e-aadd-4ca8-a93e-058b02c946c0)
<img width="511" alt="Screenshot 2024-06-30 at 12 34 48 PM" src="https://github.com/kulek1/guitar-tab-maker-issues/assets/59846310/13e6f4d2-766e-493f-b09c-5b29e4972f4a">

**Comment by kulek1** [comment]
Hey @nashsolon, 
Yes, the text box can be used for this and has been made flexible for this purpose. 
I don't plan to change the text behaviour for now, but I'll keep the issue opened for the future :)

**Comment by kulek1** [comment]
Hey @nashsolon,
I have released a new improvement for the text feature without the need to add spaces to reach the position - please let me know if it works better for you :)
