### ISSUE TITLE
Dropdown for string tunings is white text on white background

### ISSUE THREAD

**Issue by hongyuewang** [kulek1/guitar-tab-maker-issues#5]
The dropdown options for each string's tuning are not visible unless highlighted.
<img width="36" alt="image" src="https://github.com/kulek1/guitar-tab-maker-issues/assets/55165950/d494db7a-4a97-4b6e-85c4-e428651e1c8b">

**Comment by kulek1** [comment]
Thank you for reporting this bug. 
The issue has been fixed in v2.3.1 :)
