### ISSUE TITLE
an option to stop a note's playback from ringing when the next note is played

### ISSUE THREAD

**Issue by guckyslush** [kulek1/guitar-tab-maker-issues#50]
**Is your feature request related to a problem? Please describe.**
i don't know if this problem is specific to me, but when i play any tabs the notes always ring beyond whence they normally would. it ends up making everything sound really garbled like every note stacked.

**Describe the solution you'd like**
id prefer a playback option for when a new note is played, the previous note should stop playing.

**Additional context**
ive recorded a video of what im talking about and also made a mockup example video for what i want

current
https://github.com/kulek1/guitar-tab-maker-issues/assets/93175094/2ead2a69-cca2-4dfd-899f-eedbe4418c1d

my mockup
https://github.com/kulek1/guitar-tab-maker-issues/assets/93175094/2d9f4845-84f4-4742-8a7b-e546e3ed18ad
(i put a small fade between notes so it sounds better)

**Comment by kulek1** [comment]
Fixed in v5.7.4 🎉
