### ISSUE TITLE
an option to rid the minimum and maximum bpm limits!

### ISSUE THREAD

**Issue by guckyslush** [kulek1/guitar-tab-maker-issues#51]
or, to be feasible, set the minimum limit to 1 and the maximum limit to like 8400, whatever is low enough to not crash the client... 280 bpm is too slow sometimes.

**Comment by kulek1** [comment]
8400? Are you sure? 😅 
I've changed the limit to 400, which I hope will be enough for you. The change has been released in v5.7.3
