### ISSUE TITLE
Add a capo

### ISSUE THREAD

**Issue by rahimek** [kulek1/guitar-tab-maker-issues#52]
Hi, 
what do you think about adding a capo?

That will really help with some tabs :)

**Comment by kulek1** [comment]
Hi, what do you mean by saying "adding a capo"?

**Comment by rahimek** [comment]
For example:
This tabs are played with capo 7:
![image](https://github.com/kulek1/guitar-tab-maker-issues/assets/87848810/f9623870-cd7f-423b-adfd-808f9d5834d2)

If I want to do the same thing using your application, so that the sound is the same then I always have to add +7 to each sound in the tablature - and this is tiring.

**Comment by kulek1** [comment]
Okay so you would like to have a capo feature for the playback option, correct?

**Comment by rahimek** [comment]
yeah exactly

**Comment by rahimek** [comment]
or even when adding sounds, the ability to "put on" a capo:
![image](https://github.com/kulek1/guitar-tab-maker-issues/assets/87848810/81dfeb01-8760-4772-9081-214fabfbea3c)

**Comment by kulek1** [comment]
@rahimek Great news! Your feature request has been added in v5.11.0 :) 
Hope you like it! If you do, any donations to support my work would be awesome 🍻 

https://buymeacoffee.com/tabmaker

<img width="77" alt="Screenshot 2024-07-20 at 21 15 30" src="https://github.com/user-attachments/assets/e340a3b6-e086-4e31-9cbd-b4c9af6b3e6a">

**Comment by rahimek** [comment]
@kulek1 it works awesome!! Thank you very much! ;)
