### ISSUE TITLE
Palm Muting Request 

### ISSUE THREAD

**Issue by AtAnAAMeeting** [kulek1/guitar-tab-maker-issues#53]
**Is your feature request related to a problem? Please describe.** There is no specific problem other than the music I write does not sound correct without palm muting.
A clear and concise description of what the problem is.
The problem is that when I write tabs, the music does not sound good or look right without palm muting
**Describe the solution you'd like**
I would like there to be a feature on the part with the hammer on and pull off options that preferably says P.M. to go over specific notes
**Describe alternatives you've considered**
A clear and concise description of any alternative solutions or features you've considered. I have not found any alternate solutions other than to just have the music without it.

**Additional context**

**Comment by kulek1** [comment]
try the text feature: https://github.com/kulek1/guitar-tab-maker-issues/issues/33

**Comment by kulek1** [comment]
Hey @AtAnAAMeeting,
I have released a new improvement for the text feature without the need to add spaces to reach the position - please let me know if it works better for you :)
