### ISSUE TITLE
Export Header Text

### ISSUE THREAD

**Issue by DavidD003** [kulek1/guitar-tab-maker-issues#55]
The export feature only exports the rows of text pertaining to the tablature.. i.e. where the user has entered text above the tab to call out a chord name, rhythm change, lyric, or whatever, these notes are not exported

it would be nice if the text notes were exported too

**Comment by kulek1** [comment]
Hey, can you specify which export feature you're talking about? 
<img width="189" alt="Screenshot 2024-07-25 at 21 31 24" src="https://github.com/user-attachments/assets/9a8144b3-daee-4d0a-a9a3-85ea5cd47999">

**Comment by DavidD003** [comment]
Export to Text

**Comment by kulek1** [comment]
Released in v5.11.4 🎉
