### ISSUE TITLE
Ability to reorder tabs

### ISSUE THREAD

**Issue by mateusb12** [kulek1/guitar-tab-maker-issues#56]
I started creating a tab from the end of the song but now I changed my mind and want to start filling the beginning. 

In the current version I need to restart everything from scratch

But if I would be able to reorder tabs it would be so much easier

**Comment by kulek1** [comment]
<img width="191" alt="Screenshot 2024-07-28 at 13 44 39" src="https://github.com/user-attachments/assets/00641dac-4d57-4f82-ba33-f7a323c426e0">

Released in v5.12.0 🎉 
Hope you like it! If you do, any donations to support my work would be awesome 🍻
