### ISSUE TITLE
Multi line tabbing

### ISSUE THREAD

**Issue by cris-ctrl** [kulek1/guitar-tab-maker-issues#60]
If possible, could you make it so that when I'm creating a tab, instead of it continuing on and making me need to scroll the page right to see the rest, could you make it so that when the tab reach the limit of the screen, it just continues on the under-line? 

Thank you for the amazing app!

**Comment by kulek1** [comment]
Thanks for the suggestion! 🙇 
Have you tried using the `/` shortcut to divide tablature instead? It might be useful in your case :)

**Comment by cris-ctrl** [comment]
Hey that did work! sorry for my ignorance
