### ISSUE TITLE
Editing spaces

### ISSUE THREAD

**Issue by Harmonicism** [kulek1/guitar-tab-maker-issues#63]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by Harmonicism** [comment]
I can add spaces but can't remove/delete them.

**Comment by kulek1** [comment]
Did you figure this out?

**Comment by Harmonicism** [comment]
NoSent from my Galaxy
-------- Original message --------From: Mateusz ***@***.***> Date: 8/14/24  9:40 AM  (GMT-06:00) To: kulek1/guitar-tab-maker-issues ***@***.***> Cc: Harmonicism ***@***.***>, State change ***@***.***> Subject: Re: [kulek1/guitar-tab-maker-issues] Editing spaces (Issue #63) 
Did you figure this out?
