### ISSUE TITLE
Hey! Looks like you are using an adblocker

### ISSUE THREAD

**Issue by junoxp** [kulek1/guitar-tab-maker-issues#65]
**Describe the bug**
the bug is that even after turning off ad blocker it still comes up and says im running an ad blocker

**To Reproduce**
1. have ad blocker on
2. open website
3. get ad blocker warning
4. turn off ad blocker
5. get ad blocker warning interrupting use of the tab maker app

**Expected behavior**
the app should work after turning off ad blocker, i have even donated $2 for ad free link and it still does the same on the ad free link

**Desktop (please complete the following information):**
 - OS: Win 11
 - Browser Opera GX
 - Version LVL5 (core: 111.0.5168.54)

**Additional context**
i like your app and want to use it, please fix this :3

**Comment by kulek1** [comment]
Hey, what adblocker do you use? Some extensions don't turn off immediately and you may need to refresh the page a few times or even restart your browser

**Comment by junoxp** [comment]
Ublock origin

**Comment by junoxp** [comment]
I restarted the browser and it still gives me the adblocker warning

**Comment by kulek1** [comment]
I've checked your browser with uBlock Origin and it seems to work fine when TabMaker is added to the whitelist or extension is deactivated. 
Please make sure that you have `tab-maker.com` added here:
<img width="499" alt="Screenshot 2024-08-16 at 08 53 53" src="https://github.com/user-attachments/assets/ff59d7f4-22f2-4b59-a8fe-778e9a7ad97e">

and in your additional adblocker in Opera GX you can disable these toggles 
<img width="573" alt="image" src="https://github.com/user-attachments/assets/ad3041fe-cba3-4c89-b8f7-f68dad83494a">
or you can add the domain to the whitelist by clicking on Options:
<img width="696" alt="Screenshot 2024-08-16 at 09 09 26" src="https://github.com/user-attachments/assets/3cfdecb5-a6be-4584-9629-9315c5d4ed5d">

**Comment by kulek1** [comment]
I've also released a new version that doesn't show this information if someone has donated but is still using ad-blocker :)

**Comment by junoxp** [comment]
Thanks for everything, and thank you for a great app, much appreciated,
will try the fixes when I'm not all intoxed haha thx 😌

**Comment by kulek1** [comment]
Thanks man and have fun haha

**Comment by igorkozlov487** [comment]
Отключил блокировщик рекламы и все равно сайт открывается, работает только на iPhone, на компьютере не работает сайт, пробовал в браузерах Opera, Google Chrome, Yandex.
