### ISSUE TITLE
Ability to remove empty spaces?

### ISSUE THREAD

**Issue by Teslestien** [kulek1/guitar-tab-maker-issues#67]
**Is your feature request related to a problem? Please describe.**
I was trying to make some tabs for an interstellar tutorial I found on youtube and encountered a problem. I added an unnecessary empty space after a beat bar and couldn't find a way to remove that space which gives small unintentional silence that takes away some magic.

**Describe the solution you'd like**
A shortcut key like Shift+Bckspace or Ctrl+Backspace should be pretty useful.

**Describe alternatives you've considered**
Shifting all the columns to the left and changing position of the beat bar but that's a little tedious.

**Additional context**
A video of what happened: https://youtu.be/6oWQAwxbvTg

**Comment by Teslestien** [comment]
Nevermind. I will read instructions next time.

**Comment by kulek1** [comment]
Haha I wanted to say that your suggested shortcut is already implemented but I guess you found it 😄
