### ISSUE TITLE
Increase font size?

### ISSUE THREAD

**Issue by Teslestien** [kulek1/guitar-tab-maker-issues#68]
**Is your feature request related to a problem? Please describe.**
I exported a tab to pdf and the font size is way too small for me to read. I have spectacles and some eye problems.

**Describe the solution you'd like**
A setting to let me decide the font size in the exported pdf. I have tried to edit the pdf in Inkspace to make the font size bigger but it then ruins the tablature order for some reason.

**Describe alternatives you've considered**
Exporting as text and then making a pdf from word takes up too many pages.

**Additional context**
The tab I tried to print(changed extension due to github): 
[tabmaker_com-backup.txt](https://github.com/user-attachments/files/16802599/tabmaker_com-backup.txt)

**Comment by kulek1** [comment]
Hey, thanks for pointing that out! 
I’ve added a way to change the scale of exported PDFs, so hopefully, the new settings will go easy on your eyes!

<img width="456" alt="tab-maker-pdf-scale" src="https://github.com/user-attachments/assets/be616d8a-bde5-4215-9b10-0d2b90850135">

Btw. that's a really nice tab. Keep it up!
