### ISSUE TITLE
Option for the tabs to look exactly like it does in the website when exporting to PDF

### ISSUE THREAD

**Issue by angietea101** [kulek1/guitar-tab-maker-issues#69]
I prefer how the tabs are displayed on the website vs the way it looks exported. It would be awesome if users had the option to choose the way it looks.

**Comment by kulek1** [comment]
If you want to have tabs with website styling, you can use the `Print / PDF` option. 
Unfortunately, it is not possible to change the styling of generated PDF from `Export to PDF` option.
