### ISSUE TITLE
Custom instruments

### ISSUE THREAD

**Issue by Kopplog** [kulek1/guitar-tab-maker-issues#71]
** finding your app highly useful in principle, I play another instruments wth some other tunings and string count **

Hi, I'm playing some rare instruments with 5 string and 10 strings with several rare tunings and setups (tunings getting lower and higher). Gamba De Viola's would have a tuning up on thirds (like mine), violins will have them in fifth, etc. I'd find it to be greatly helpful if your app had a custom setup editor for, call it custom instruments - and features including: 
** the amount of strings** (like, add/remove another string) and be able to **tune it per string** (down and up)

Cheers. I'd be willing to tip you for this showing you my support. Your app shows great potential for quickly setting up finger training licks, basically. Love it!

**Comment by kulek1** [comment]
Thanks for the suggestion! I'm adding it to my todo list :)

**Comment by kulek1** [comment]
@Kopplog your suggestion has been implemented as additional 5, 9 & 10-string instruments:
<img width="466" alt="Screenshot 2024-09-27 at 17 11 16" src="https://github.com/user-attachments/assets/90264652-3202-4024-863a-c40c3c032446">

That should cover all of your cases :)
