### ISSUE TITLE
Tab displayed, "upside-down"?

### ISSUE THREAD

**Issue by PJH-JR** [kulek1/guitar-tab-maker-issues#72]
As a long-time guitar-playing-programmer, I don't understand the concept of tablature showing the top string to be the, "Low" E string.
Perhaps this is right-handed privilege, but as I play, the, "Low" E string is on top (farthest from the floor).
That is how I have been accustomed to reading tab for lo these many years...
I expect the 1st position E chord to be noted as
022100
I see in the diagram, the equivalent of:
001220
Show vertically
Expected  Displayed 
.......0...................0
.......2...................0
.......2...................1
.......1...................2
.......0...................2
.......0...................0

https://www.facebook.com/photo/?fbid=8544077418963701&set=a.241427515895441

It's a puzzler... thanks

**Comment by kulek1** [comment]
Hey, to be completely honest, I've never seen tabs that are "upside-down".
TabMaker follows the most common notation where lowest E in standard tuning is on the bottom.
