### ISSUE TITLE
To be able to remove columns

### ISSUE THREAD

**Issue by SuNG0D** [kulek1/guitar-tab-maker-issues#73]
**Is your feature request related to a problem? Please describe.**
Yes, basically columns get added automatically when you add a note to the column you're selecting, but that messes with the pace of the song that I'm writing and I'm not able to remove the columns, so I have to be very precise with what I do. If I add a note by error I need to remove the whole tab and start again, that's very annoying.

**Describe the solution you'd like**
A button that simply removes the column that you're selecting

**Describe alternatives you've considered**
Couldn't think of an alternative, sorry.

**Comment by SuNG0D** [comment]
Didn't mention that you could do the same to add a column

**Comment by kulek1** [comment]
<img width="466" alt="image" src="https://github.com/user-attachments/assets/331b1620-f267-4777-92f4-72edd610f3fd">

I recommend to use keyboard shortcuts to remove column or to change insert mode☝️

**Comment by SuNG0D** [comment]
Didn't see that, thanks for the help!
