### ISSUE TITLE
Won’t let me export

### ISSUE THREAD

**Issue by im-emanuel** [kulek1/guitar-tab-maker-issues#74]
For some reason I can’t export at all
![IMG_0094](https://github.com/user-attachments/assets/11a9eceb-3875-451b-9211-da74f49bc1b4)

At the bottom right none of those options work and when I press on any of the, it doesn’t do anything.
Can I please get help.

**Comment by kulek1** [comment]
Hey, 
Have you tried to refresh the page and use different browser like Safari? 
What's the name of your browser?

**Comment by im-emanuel** [comment]
I'm using Google

**Comment by kulek1** [comment]
I haven't found any issues related to the functionality apart from incorrect / not visible link colours in the dark mode. I pushed a small fix so try to refresh the page and let me know if it works :)

**Comment by im-emanuel** [comment]
It works now thank you very much for the help.
