### ISSUE TITLE
Tab title bar doesn't work on Firefox

### ISSUE THREAD

**Issue by rusandris** [kulek1/guitar-tab-maker-issues#77]
When adding a new tab, the title bar above it behaves weirdly. 

The length of the text box is limited to the length of the tab, so it is not possible to enter a title that is longer than a couple of characters right away. 
Also, when clicking on the title text box, the cursor appears wherever (instead of the beginning or end of the title).

Desktop:
 - OS: Ubuntu
 - Browser: Firefox

**Comment by kulek1** [comment]
Hey,
From your description, the feature works as expected. The length is limited to the length of the tab and you can add letters anywhere. Before this change, you had to add a lot of spaces to insert a chord in the middle of the tab, for example.

**Comment by rusandris** [comment]
Hi!
I like to add a title before adding any notes so I don't get confused. Wouldn't it be reasonable to detach the length of title from the length of the tab and give the user a longer text box than just six characters? After 5-6 characters it goes into insert mode and starts replacing characters. Plus when I accidentally click at the end of the text box, it only allows one character and it goes immediately into insert mode.

**Comment by kulek1** [comment]
Yes, I did that on purpose to be able to implement the way the text feature works. However, I understand your point and have made some improvements to cover your case. 
Please let me know if this version works better for you: 
https://beta.tab-maker.com/en/app

**Comment by rusandris** [comment]
Fantastic! Thanks for the quick replies!

**Comment by kulek1** [comment]
> Fantastic! Thanks for the quick replies!

Let me know if it works and I'll release it to the app ;)

**Comment by rusandris** [comment]
> Let me know if it works and I'll release it to the app ;)

Works like a charm, thanks again!

**Comment by kulek1** [comment]
That's great to hear! I'll release it in the next version then
