### ISSUE TITLE
Can I highlight and copy parts of the tab I'm writing?

### ISSUE THREAD

**Issue by Carlosjoya88** [kulek1/guitar-tab-maker-issues#79]
Sometimes I need to copy and paste certain parts of the tab I'm writing. 

I'm not sure if this feature is available but I couldn't find it. Would be very nifty to have

thank you

**Comment by kulek1** [comment]
Hey @Carlosjoya88,
You can copy/paste single columns with keyboard shortcuts:
<img width="472" alt="image" src="https://github.com/user-attachments/assets/4cccf99d-f498-425e-bdd5-c052f9a79d18">

**Comment by Carlosjoya88** [comment]
Thanks I’ll try it out -J. CarlosOn Oct 10, 2024, at 10:47 PM, Mateusz ***@***.***> wrote:﻿
Hey @Carlosjoya88,
You can copy/paste single columns with keyboard shortcuts:
image.png (view on web)
