### ISSUE TITLE
PDF Tab export not exporting correctly 

### ISSUE THREAD

**Issue by Carlosjoya88** [kulek1/guitar-tab-maker-issues#80]
Man this software has a lot of potential. However I wrote a pretty long tab and when it was time to export it in large format it was missing about half the rest of the page. Any idea why this happens?

**Comment by kulek1** [comment]
To be honest, I don't see this tab, so it's hard to say. First of all, please provide a link to the problematic tab

**Comment by Carlosjoya88** [comment]
How would I be able to do that? It brings me to my next question can you email a tab you created to someone? -J. CarlosOn Oct 11, 2024, at 8:08 AM, Mateusz ***@***.***> wrote:﻿
To be honest, I don't see this tab, so it's hard to say. First of all, please provide a link to the problematic tab

**Comment by kulek1** [comment]
@Carlosjoya88 you can try this option:
<img width="523" alt="Screenshot 2024-10-12 at 09 39 14" src="https://github.com/user-attachments/assets/4f004548-0154-4e0f-9707-fcbcb28055dc">
