### ISSUE TITLE
Custom tunings for AI detection

### ISSUE THREAD

**Issue by jay-addinsall** [kulek1/guitar-tab-maker-issues#81]
**Is your feature request related to a problem? Please describe.**
I am trying to tab out [this](https://www.youtube.com/watch?v=_QuFM6Ogiyg) song, as the tabs don't currently exists. I'm using the MP3 AI detector to help with the tabs.

The artist Max mentioned that the song uses the tuning BGDGAD, however this is a super custom tuning and Tabmaker doesn't have it as a preset. 

Right now when I use the AI tab detector, it tabs the song in standard tuning, so the tabs and chord shapes are a bit crazy haha.

**Describe the solution you'd like**
I'm hoping to be able to:

1. Enter a custom tuning (it currently says that this can be done, but I don't really understand the instructions and can't figure out how to do this) and,
2. Be able to have the AI detect the tabs _**using the custom tuning set**_

**Describe alternatives you've considered**
I originally ran into this issue when using the detector, and it tabbed in standard tuning. I tried to resolve by creating a tab from scratch using the custom tuning (as I had assumed that the detector just used whatever tuning was already set in the tab), but this is where i ran into the custom tuning issues

**Additional context**
I think that's everything! Let me know if you need any clarification. Also just wanted to quickly say that I love this project so so much! I use Tabmaker all the time and think it's one of the best and most accessible resources for tabbing. I'm a self taught dev, so this project has inspired me to continue working on my own projects, and making tools that are as free and accessible as this one. So thank you!!

**Comment by kulek1** [comment]
Hey @jay-addinsall,
You can set any custom tuning by clicking on open notes on the guitar fret:
<img width="145" alt="image" src="https://github.com/user-attachments/assets/350b39aa-fc55-4b77-8a3c-5f4188dbaf4b">

After that, AI Music to Tabs will generate tabs based on the current tuning :)
Let me know if it worked.

Cheers!
