### ISSUE TITLE
Ad Blocker Problems

### ISSUE THREAD

**Issue by mrawesomesauce** [kulek1/guitar-tab-maker-issues#82]
**BUG REPORT**

The website includes a feature that displays a pop-up message instructing users to disable their ad blocker. After disabling the adblock (in my case, uBlock Origin) in Chrome settings and refreshing the page, the pop-up continues to appear. I also opened a new tab with the same website, but the issue persisted. Despite having turned off the ad blocker and seeing ads on the page, the pop-up remains active.

**EXPECTED BEHAVIOR**

I anticipated that the website would function without displaying the pop-up after disabling uBlock, but it continues to appear.

**DESKTOP**

 - Chromebook
 - Chrome
 - 130.0.6723.91/92

**Comment by kulek1** [comment]
Hey, please check if you don't have any other Chrome extensions or DNS ads-blockers on your network that could cause this. 
I use the same browser and adding the domain to the whitelist in uBlock Origin doesn't cause any problems.
