### ISSUE TITLE
invert note selection please

### ISSUE THREAD

**Issue by mirddes** [kulek1/guitar-tab-maker-issues#83]
![image](https://github.com/user-attachments/assets/c309045a-493b-4dac-b688-96ff6cb46c05)

it's breaking my head. the highest notes need to be at the top of the screen instead of the bottom please.

it actually physically hurts.

please and thank you. 

your website is great btw.

**Comment by kulek1** [comment]
I got those high notes back on top where they belong in the latest release. Thanks for the heads-up lol
