### ISSUE TITLE
i just want to be able to see all of the UI 100% of the time, i have a massive high resolution display.

### ISSUE THREAD

**Issue by mirddes** [kulek1/guitar-tab-maker-issues#84]
![image](https://github.com/user-attachments/assets/7a4f4579-7355-4ac1-9737-0900b9b1587a)

so if we could have both of these pictured elements mutually accessible that would be lovely, would greatly improve workflow of anyone trying to use anything more than a small handful of anything more than basic notes.

needing to repeat the hiding/unhiding process is burdensome and often results in the notes getting hidden entirely when i minimized the wrong panel.

**Comment by kulek1** [comment]
That's a great idea! I'll try to find a suitable way to implement it. :)

**Comment by kulek1** [comment]
@mirddes Please take a look at the latest version. I believe I've slightly improved the current user experience and addressed your concern as well.
