### ISSUE TITLE
Export to PDF - exports only 1 row

### ISSUE THREAD

**Issue by Varg29A** [kulek1/guitar-tab-maker-issues#85]
**Describe the bug**
I'm trying to export my tab to PDF but the exported file has only 1 row of tabs. Same for the both options of Export to PDF

**To Reproduce**
1. AI > load mp3 file
2. Export Tabs > Print / PDF

**Expected behavior**
I expected to get full tabs of the song

**Screenshots**
![image](https://github.com/user-attachments/assets/3bc22e36-7b4d-47f0-b99f-f903a20bd5df)
![image](https://github.com/user-attachments/assets/d03047e3-e8a3-4b9d-b9a0-0bcd01ea4f7f)
the song is ~2 min long

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome
 - Version 131.0.6778.86

**Additional context**

**Comment by kulek1** [comment]
Thanks for the report!
For now, please split tabs by using `/` shortcut because I'm not sure when this feature will be implemented

**Comment by kulek1** [comment]
The feature has been implemented and released 🎉
