### ISSUE TITLE
Scroll bar doesn't work

### ISSUE THREAD

**Issue by Varg29A** [kulek1/guitar-tab-maker-issues#86]
**Describe the bug**
The scroll bar at the bottom of the screen is not active, so I can't scroll the tabs to the right, although there are tabs. The song is 2 min long and the tab maker plays it, but the tabs are not on the screen

**To Reproduce**
1. Import any long song
2. Try to scroll to the right

**Screenshots**
![image](https://github.com/user-attachments/assets/c70cb0f9-8a16-4ec3-800f-266f9cd64aed)
I circled with red the buttons which are not working

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome
 - Version 131.0.6778.86

**Comment by kulek1** [comment]
Thanks for the report! 
The issue has been fixed 🎉
