### ISSUE TITLE
12 string guitarra???

### ISSUE THREAD

**Issue by ValientoFV** [kulek1/guitar-tab-maker-issues#87]
I am always sad when I remember you have no 12 string on the website. I would love if you added one that is tuned to sound like corridos. Especially if its a takamine. !!!!

**Comment by kulek1** [comment]
Don't be sad! I added 12-string guitar for you 😇

<img width="357" alt="Screenshot 2024-12-09 at 18 32 04" src="https://github.com/user-attachments/assets/c12ecd19-1580-49bf-902c-2a2e96955f58">
