### ISSUE TITLE
Delete a column (in tablature)

### ISSUE THREAD

**Issue by 33kc** [kulek1/guitar-tab-maker-issues#89]
**Is your feature request related to a problem? Please describe.**
![image](https://github.com/user-attachments/assets/791ae67b-3afc-45c8-a0e2-0e8668ee5c8f)
(first attached image), you can see empty columns in the tab (blank space).
there is no way to get rid of these individual empty columns, there is an alternative, where we can make a new tab and manually copy everything over (leaving the empty columns), but when you have long tabs, it becomes time consuming and just disrupts the overall structure

**Describe the solution you'd like**
![image](https://github.com/user-attachments/assets/8d340575-db30-436b-8b06-97dfcfaa193d)
 (second image), having the  "Delete Column" button there would be nice

**Describe alternatives you've considered**
 creating a new tab and manually copying the previous tab (ignoring empty column)

**Comment by kulek1** [comment]
You can use an existing keyboard shortcut for it:
<img width="494" alt="Screenshot 2024-12-14 at 16 49 15" src="https://github.com/user-attachments/assets/93024862-7176-4513-b24d-176039dfb8d0" />
