### ISSUE TITLE
Bass tab

### ISSUE THREAD

**Issue by DAVEinNOLA** [kulek1/guitar-tab-maker-issues#9]
It would be nice to be able to remove the top two lines to provide for bass tabs

**Comment by kulek1** [comment]
Hey @DAVEinNOLA, the support for bass has been added in v3.7.0 🎉

<img width="487" alt="Screenshot 2024-01-16 at 19 25 45" src="https://github.com/kulek1/guitar-tab-maker-issues/assets/7605514/433888ae-b294-4ae5-a77b-c0604d1651a6">

**Comment by DAVEinNOLA** [comment]
Thank you!
David Butler
***@***.***

 

    On Tuesday, January 16, 2024 at 12:26:29 PM CST, Mateusz ***@***.***> wrote:  
 
 


Hey @DAVEinNOLA, the support for bass has been added in v3.7.0 🎉
Screenshot.2024-01-16.at.19.25.45.png (view on web)
