### ISSUE TITLE
Import any songs tab 

### ISSUE THREAD

**Issue by ValientoFV** [kulek1/guitar-tab-maker-issues#90]
**Is your feature request related to a problem? Please describe.**
I'm always angry when I want to import a song tab into tab maker and the AI is not accurate at all so I cannot use that to import a song.

**Describe the solution you'd like**
I would love if you could add a feature to import a file of a tab to any song.

**Describe alternatives you've considered**
I tried using the AI song file feature and that has never been accurate

**Additional context**

**Comment by kulek1** [comment]
Thanks for the suggestion. Unfortunately, I'm not planning to support this feature any time soon.
